### ISSUE TITLE
关于自动备份

### ISSUE THREAD

**Issue by Neck1ace** [hjh142857/scripts#1]
大佬好，想问一下为什么FTP备份配置设置好了但是不自动备份到FTP。

**Comment by hjh142857** [comment]
1. 有没有按照这个要求填写？
> FTP_URL=ftp://your_ftp_url/your_folder/    # FTP备份地址，必须以/结尾，否则会出现错误。不设置本项则禁用远程FTP备份
2. 有没有更改bitwarden的docker的tag，有些版本的bitwarden系统底包可能不带curl，脚本ftp备份是基于curl的

**Comment by Neck1ace** [comment]
大佬，第2点该如何操作呢？

**Comment by hjh142857** [comment]
emm。。第二点已经不重要了。。刚刚我检查了下代码。。有个地方我本地改了忘记同步了，现在拉取最新的bitwarden.sh就可以了。。测试过了是没问题的。。尴尬ing。。。
