### ISSUE TITLE
部署后一个小时数据被重置

### ISSUE THREAD

**Issue by hotsymbol** [hjh142857/scripts#2]
部署后一个小时数据被重置，账户也被删除。

**Comment by hjh142857** [comment]
默认10分钟备份一次的，进web ssh里面看看备份的文件有没有。另外f1免费计划会自动停止，直到下一次访问才激活，有一种可能是新建账户10分钟内自动停止了，配置文件没备份下来，激活时恢复的是新建账户之前的配置。可以把自动备份时间改短一点比如2分钟1分钟的样子，当然，还等注意看看cpu使用会不会超免费配额
