### ISSUE TITLE
bitwarden升级，重新部署运行后，backup_daily文件夹里面没有备份文件。

### ISSUE THREAD

**Issue by kdsbls** [hjh142857/scripts#3]
_bitwarden升级vaultwarden，重新部署运行后，backup_daily文件夹里面没有备份文件，导致ftp备份也为空，设置参数为默认：DAILY_BAK_COUNTS=5。请问怎么解决，谢谢。

**Comment by hjh142857** [comment]
每天北京时间0点才会有daily backup
