### ISSUE TITLE
大佬不好意思，再请问每天0点生成backup_daily后，backup_realtime就停止备份

### ISSUE THREAD

**Issue by kdsbls** [hjh142857/scripts#4]
大佬不好意思，再请问每天0点生成backup_daily后，backup_realtime就停止备份，修改备份REALTIME_BAK_CYCLE数字后譬如10改12或者15、20等，保存后才会从修改的时间后开始备份。不知道怎么办？谢谢。

**Comment by hjh142857** [comment]
看了下我自己的web app，没能复现。可能你的保活没做好，web app自动停止了备份自然也就停了。真心的建议你考虑下买个服务器用docker版的吧，azure web app折腾可能不适合你。

**Comment by kdsbls** [comment]
确实，吃灰小鸡有好几个挂探针，但总觉得没有azure稳啊。我把REALTIME_BAK_CYCLE改成12，uptimerobot 10改成5再试试。希望能解决。谢谢回复。
