### ISSUE TITLE
拉取1.25.0之后版本的镜像，会提示程序运行错误。

### ISSUE THREAD

**Issue by sde31c** [hjh142857/scripts#6]
拉取vaultwarden 1.25.0之后的镜像版本时无法正常运行，访问vaultwarden网页版时会提示：
:( Application Error
If you are the application administrator, you can access the [diagnostic resources]

**Comment by hjh142857** [comment]
好久没更新了，瞅了一下
1.25.1开始docker-compose.yml需要加上环境变量I_REALLY_WANT_VOLATILE_STORAGE=true
1.26.0开始docker-compose.yml还需要删去entrypoint: ["/usr/bin/dumb-init","--"]这一行

**Comment by hjh142857** [comment]
已经更新了相关说明，测试了下从1.25.1到最新的1.28.1都没问题了

**Comment by sde31c** [comment]
> 已经更新了相关说明，测试了下从1.25.1到最新的1.28.1都没问题了

多谢大佬更新~
刚看了眼日志里有个人地址，我把日志编辑掉了。。。
